apiVersion: 1
datasources:
  - name: RisingWave
    type: grafana-postgresql-datasource
    uid: risingwave
    url: risingwave:4566
    user: root
    isDefault: true
    jsonData: { database: dev, sslmode: disable }
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    jsonData: { timeInterval: 15s }
  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
